// src/components/footer/footer.tsx
import {
  Title,
  Text,
  Group,
  Button,
  Divider,
  Container,
  Anchor,
  Box,
  useMantineTheme,
  Stack,
} from "@mantine/core";

import EthischeCode from "../../assets/docs/2022-ethische-code-phoenix-opleidingen-voor-deelnemers.pdf";
import LeveringsVoorwaarden from "../../assets/docs/Leveringsvoorwaarden.pdf";
import { Link } from "react-router-dom";

const Footer: React.FC = () => {
  const theme = useMantineTheme();

  const contactGegevens = [
    "Mirjam Kroon-Hoekendijk",
    "Dorpsweg 71",
    "4223 ND",
    "Hoornaar",
    "Zuid-Holland",
    "mirjam@kroontrainingadvies.com",
    "0653507815",
  ];

  const links = [
    {
      label: "Algemene voorwaarden",
      link: LeveringsVoorwaarden,
    },
    {
      label: "Ethische code",
      link: EthischeCode,
    },
  ];

  return (
    <Box bg={theme.colors.custom[2]} c="white" pt="md">
      <Container>
        <Group justify="space-between" pb="lg">
          <Title order={1}>Contact</Title>

          <Link to="/contact">
            <Button>Neem contact op</Button>
          </Link>
        </Group>

        {contactGegevens.map((gegeven) => (
          <Text key={gegeven}>{gegeven}</Text>
        ))}

        <Divider my="lg" color="white" size="xs" />

        <Group justify="space-between" align="flex-end" pb="lg">
          <Stack>
            {links.map((link) => (
              <Anchor
                key={link.label}
                href={link.link}
                target="_blank"
                underline="always"
              >
                {link.label}
              </Anchor>
            ))}
          </Stack>

          <Anchor href="https://www.kibbelingmedia.nl/" target="_blank">
            2023 Kibbeling Media. All rights reserved.
          </Anchor>
        </Group>
      </Container>
    </Box>
  );
};

export default Footer;

// src/lib/components/Footer.svelte
<script lang="ts">
  const contactGegevens = [
    'Mirjam Kroon-Hoekendijk',
    'Dorpsweg 71',
    '4223 ND',
    'Hoornaar',
    'Zuid-Holland',
    'mirjam@kroontrainingadvies.com',
    '0653507815',
  ];
</script>

<footer>
  <div class="container">
    <div class="footer-top">
      <h1>Contact</h1>
      <a href="/contact" class="btn">Neem contact op</a>
    </div>

    {#each contactGegevens as gegeven}
      <p>{gegeven}</p>
    {/each}

    <hr class="divider" />

    <div class="footer-bottom">
      <div class="footer-links">
        <a href="/assets/docs/Leveringsvoorwaarden.pdf" target="_blank">Algemene voorwaarden</a>
        <a href="/assets/docs/MirjamKroonTrainingEthischecode.pdf" target="_blank">Ethische code</a>
      </div>
      <a href="https://www.kibbelingmedia.nl/" target="_blank">2023 Kibbeling Media. All rights reserved.</a>
    </div>
  </div>
</footer>

<style>
  footer {
    background-color: var(--color-blue);
    color: white;
    padding: 1rem 0 2rem;
  }

  .footer-top {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding-bottom: 1rem;
  }

  p {
    margin: 0.15rem 0;
  }

  .divider {
    border: none;
    border-top: 1px solid white;
    margin: 1.5rem 0;
  }

  .footer-bottom {
    display: flex;
    justify-content: space-between;
    align-items: flex-end;
    flex-wrap: wrap;
    gap: 1rem;
  }

  .footer-links {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }

  a {
    color: white;
    text-decoration: underline;
  }

  .btn {
    text-decoration: none;
  }
</style>
